# 监听指定网卡（在 host 网络下有效，请替换为你的实际网卡名）
interface=enp1s5
bind-interfaces
dhcp-range=::,static

# DHCP 地址池（根据你的实际网段修改）
dhcp-range=192.168.1.50,192.168.1.100,255.255.255.0,12h
dhcp-option=3,192.168.1.1
dhcp-option=6,192.168.1.1,223.5.5.5

# 启用 TFTP 服务
enable-tftp
tftp-root=/var/tftp

# 架构识别（PXE Client Architecture Option 93）
dhcp-match=set:bios,option:client-arch,0        # Legacy BIOS
dhcp-match=set:efi64,option:client-arch,7       # UEFI x64 (EFI BC)
dhcp-match=set:efi64,option:client-arch,9       # UEFI x64 (EFI x86_64)

# 引导文件分发（带标签的规则必须放在默认规则之前）
dhcp-boot=tag:efi64,snponly.efi                    # UEFI → snponly.efi
dhcp-boot=tag:bios,undionly.kpxe                # Legacy → undionly.kpxe

# 识别UEFI iPXE 二次请求，下发下一跳引导文件 boot.ipxe
dhcp-userclass=set:ipxe,iPXE
dhcp-boot=tag:ipxe,boot.ipxe

# 静态主机名分配（用于 iSCSI IQN 动态生成）
# 指定额外读取的主机配置文件
dhcp-hostsfile=/etc/dnsmasq.d/dhcp-hosts.conf
dhcp-leasefile=/var/lib/misc/dnsmasq.leases

# 日志（调试用）
log-dhcp
log-queries