services:

  ipxe-dnsmasq:
    image: jpillora/dnsmasq:latest
    container_name: dnsmasq-pxe
    network_mode: host          # 必须使用 host 网络（DHCP/TFTP 需要）
    cap_add:
      - NET_ADMIN              # 需要网络权限
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./tftpboot:/var/tftpboot:ro
    restart: unless-stopped
    # 调试时可加：command: ["--no-daemon", "--log-queries", "--log-dhcp"]

  ipxe-iscsi:
    image: wtnb75/stgt
    container_name: ipxe-iscsi
    restart: unless-stopped          # 容器自动重启（除非手动停止）
    network_mode: host               # 使用 host 网络模式（直接使用宿主机网络）
    privileged: true                 # 特权模式（允许访问硬件设备）
    volumes:
      - /etc/target:/etc/target
      - /run/lvm:/run/lvm
      - /lib/modules:/lib/modules
      - /sys/kernel/config:/sys/kernel/config
      - /dev:/dev
      - ./iscsi/img:/home/iscsi_img  # 挂载 iSCSI 存储镜像目录
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

  nginx:
    image: nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "88:80"
    restart: unless-stopped