user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    # 核心：默认类型强制为二进制流，防止 Nginx 根据后缀瞎猜
    default_type  application/octet-stream;

    # iPXE 核心优化：关闭零拷贝和 TCP 积压，防止大包冲垮 iPXE 接收缓冲区
    sendfile off;
    tcp_nopush off;
    tcp_nodelay on;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    keepalive_timeout  65;
    
    # 关闭 gzip，iPXE 处理不了压缩流
    gzip off;

    include /etc/nginx/conf.d/*.conf;
}