server {
    listen 80;
    server_name localhost;

    # 直接指向存放镜像的根目录（对应 docker-compose 中的挂载点）
    root /usr/share/nginx/html;

    location / {
        # 开启目录浏览，方便你在浏览器里查看文件列表
        autoindex on;
        autoindex_exact_size off; # 显示人类可读的大小 (KB/MB)
        autoindex_localtime on;
        
        # 再次强调：强制所有文件作为纯二进制流下载
        default_type application/octet-stream;
    }
}